[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["LeoWu <122122171+Bunny1780@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
