# Generated by Django 5.0.4 on 2024-04-25 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanny', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nanny',
            old_name='descriotion',
            new_name='description',
        ),
    ]
