# Generated by Django 5.0.4 on 2024-04-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanny', '0002_rename_descriotion_nanny_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
