# Generated by Django 5.0.4 on 2024-04-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanny', '0003_alter_nanny_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanny',
            name='nikename',
        ),
        migrations.RemoveField(
            model_name='nanny',
            name='tel',
        ),
    ]
